### ISSUE TITLE
@ionoc/cloud-angular does not work with Rollup

### ISSUE THREAD

**Issue by rolandjitsu** [driftyco/ionic-cloud-angular#35]
I have an Ionic app that's setup to use Rollup as bundler and it seems that during the build, rollup cannot find the module:
```text
10:34:02]  ionic-app-scripts 1.0.0 
[10:34:02]  build prod started ... 
[10:34:02]  clean started ... 
[10:34:02]  clean finished in 6 ms 
[10:34:02]  copy started ... 
[10:34:02]  ngc started ... 
[10:34:19]  ngc finished in 16.13 s 
[10:34:19]  rollup started ... 
[10:34:19]  copy finished in 16.38 s 
[10:34:26]  rollup failed: Could not resolve '@ionic/cloud-angular' from 
            /Users/rolandjitsu/Projects/infarm/maintenance/src/app/app.module.ts 
[10:34:26]  ionic-app-script task: "build" 
[10:34:26]  Error: Could not resolve '@ionic/cloud-angular' from 
            /Users/rolandjitsu/Projects/infarm/maintenance/src/app/app.module.ts 
Error: Could not resolve '@ionic/cloud-angular' from /Users/rolandjitsu/Projects/infarm/maintenance/src/app/app.module.ts
    at Error (native)
    at /Users/rolandjitsu/Projects/infarm/maintenance/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /Users/rolandjitsu/Projects/infarm/maintenance/node_modules/browser-resolve/index.js:265:24
    at /Users/rolandjitsu/Projects/infarm/maintenance/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:14
    at process (/Users/rolandjitsu/Projects/infarm/maintenance/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/rolandjitsu/Projects/infarm/maintenance/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/rolandjitsu/Projects/infarm/maintenance/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/rolandjitsu/Projects/infarm/maintenance/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/rolandjitsu/Projects/infarm/maintenance/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Webpack seems to work just fine, but the problem is that with Webpack I cannot have env variables passed to the app when the app is build for production (something about the AOT), so I need to use Rollup at the moment.

System Info:
```text
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by wursta** [comment]
+1

**Comment by rolandjitsu** [comment]
Closing this as there is a PR with a fix.
