### ISSUE TITLE
Version 0.10.0 - Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by arsyed04** [driftyco/ionic-cloud-angular#42]
Runtime Error
Object prototype may only be an Object or null: undefined
Stack
```
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (http://localhost:8100/build/main.js:107679:9)
    at http://localhost:8100/build/main.js:107776:5
    at Object.<anonymous> (http://localhost:8100/build/main.js:107781:2)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:96292:79)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:130015:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
```

Ionic Framework: 2.0.1
Ionic Native: 2.4.1
Ionic App Scripts: 1.0.0
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 7.4.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

If I downgrade to 0.5.0 it works.
Fresh project works fine though.

**Comment by arsyed04** [comment]
It is breaking 0.9.0 onwards.

**Comment by alexciesielski** [comment]
0.9.1 works fine for me so it must be something on your side.

**Comment by arsyed04** [comment]
It is fine after 0.11.0

**Comment by janpio** [comment]
Could you close this issue then, @arsyed04, please? Thanks.

**Comment by c0bra** [comment]
I'm getting this exact error with this setup:

```
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

System:

    Node : v6.9.2
    npm  : 5.3.0
    OS   : macOS Sierra
```

After pausing on the exception it seems like it's due to something improperly providing the wrong class definition to an extension call (with webpack?).

I have a class definition that's like `export class DetailPage extends AuthPage`, but in the debugger I see `AuthPage` is from `priority.actions.ts` which is an ngrx actions class, something COMPLETELY different and not referenced in that file in any way.

How the hell is this happening?

# Update

After re-ordering pretty much every single `import` statement in my app it's now working. I can only assume typescript/webpack (or the combination of both) were barfing due to some unmentioned import order requirement.
