### ISSUE TITLE
rollup failed: Unexpected token

### ISSUE THREAD

**Issue by mobyjames** [driftyco/ionic-cloud-angular#44]
Running into this issue when trying to build with the module included via `CloudModule.forRoot`.

Followed all the instructions here: http://docs.ionic.io/setup.html but can't seem to get around it.

Node v7.4.0
NPM 4.0.5

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

Full Error Dump:

```
[16:18:13]  rollup failed: Unexpected token
[16:18:13]  ionic-app-script task: "build"

[16:18:13]  Error: Unexpected token
Error: Unexpected token
    at error (/Users/james/Projects/iCanQuit-App/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/Users/james/Projects/iCanQuit-App/node_modules/rollup/dist/rollup.js:7997:2)
    at tryParse (/Users/james/Projects/iCanQuit-App/node_modules/rollup/dist/rollup.js:7700:10)
    at new Module (/Users/james/Projects/iCanQuit-App/node_modules/rollup/dist/rollup.js:7735:14)
    at /Users/james/Projects/iCanQuit-App/node_modules/rollup/dist/rollup.js:9481:17
```

**Comment by vovikdrg** [comment]
I have same problem

**Comment by vovikdrg** [comment]
@mobyjames  I have find out issue. Issue is that angular-cloud has dependency to rxjs beta, after i upgraded to 5.0.1 issue is gone.
